name: Test and Build

on:
    push:
        branches:
            - "*"

env:
    PLUGIN_NAME: share-to-notionnext # Change this to match the id of your plugin.

jobs:
    build:
        name: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Build
              id: build
              run: |
                  npm install
                  npm run build
                  mkdir ${{ env.PLUGIN_NAME }}
                  cp main.js manifest.json ${{ env.PLUGIN_NAME }}
                  zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
                  ls
                  echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_OUTPUT
